on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up Go 1.18.3
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.3
        id: go
      
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go modules
        run: go mod download -x

      - name: build linux-server-amd64-server
        run: GOOS=linux GOARCH="amd64" go build -a -v -installsuffix cgo -ldflags="-w -s" -o go-ipam-linux-server-amd64 cmd/server/*.go
      
      - name: build linux-client-amd64-client
        run: GOOS=linux GOARCH="amd64" go build -a -v -installsuffix cgo -ldflags="-w -s" -o go-ipam-linux-client-amd64 cmd/client/*.go


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/go-ipam
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Docker build & push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
#          ,linux/arm64
          cache-to: ghcr.io/${{ github.repository }}/go-ipam:cache
          cache-from: ghcr.io/${{ github.repository }}/go-ipam:cache
          network: host

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ghcr.io/${{ github.repository }}/go-ipam:${{ steps.tag.outputs.tag }}
      
      - name: save linux-server-amd64 artifact in Actions
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux-server-amd64
          path: go-ipam-linux-server-amd64
      
      - name: save linux-client-amd64 artifact in Actions
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux-client-amd64
          path: go-ipam-linux-client-amd64

      - name: upload linux-server-amd64 release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-ipam-linux-server-amd64
          asset_name: go-ipam-linux-server-amd64
          asset_content_type: application/binary
      
      - name: upload linux-client-amd64 release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-ipam-linux-client-amd64
          asset_name: go-ipam-linux-client-amd64
          asset_content_type: application/binary


